import { TimetableEntry, Subject, Faculty, TimeSlot } from './types';

export const INITIAL_TIME_SLOTS: TimeSlot[] = [
  { period: 1, startTime: '09:00 AM', endTime: '10:00 AM' },
  { period: 2, startTime: '10:00 AM', endTime: '11:00 AM' },
  { period: 3, startTime: '11:15 AM', endTime: '12:15 PM' },
  { period: 4, startTime: '12:15 PM', endTime: '01:15 PM' },
  { period: 5, startTime: '01:15 PM', endTime: '02:15 PM' },
  { period: 6, startTime: '02:15 PM', endTime: '03:15 PM' }
];

export const INITIAL_SUBJECTS: Subject[] = [
  { subjectCode: 'S11BLH11', subjectName: 'Programming in C', department: 'CSE', year: 'I' },
  { subjectCode: 'S11BPB51', subjectName: 'Augmented and Virtual Reality', department: 'CSE', year: 'III' },
  { subjectCode: 'SCSB2501', subjectName: 'Computer Networks lab', department: 'CSE', year: 'III' },
  { subjectCode: 'S11BLH51', subjectName: 'Software Engineering Design and Development', department: 'CSE', year: 'III' },
  { subjectCode: 'S12BLH31', subjectName: 'Programming in Java', department: 'CSE', year: 'II' }
];

export const INITIAL_FACULTY: Faculty[] = [
  { facultyId: 'F01', name: 'Dr.L.K.Joshila Grace', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F02', name: 'Ms.D.Devi', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F03', name: 'Dr.N.Sridevi', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F04', name: 'Ms.P.Malathi', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F05', name: 'Dr.P.Privietha', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F06', name: 'Ms.R.Velvizhi', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F07', name: 'Ms.D.Aishwarya', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F08', name: 'Dr.B.Gracelin Sheena', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F09', name: 'Dr.V.Nirmalrani', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F10', name: 'Dr.M.Mahasree', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F11', name: 'Dr.Shamreen Ahamed.B', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F12', name: 'Dr.G.Subathra', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F13', name: 'Dr.Srideivanai Nagarajan', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F14', name: 'Dr.Ramya G.Franklin', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F15', name: 'Dr.R.Asha', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F16', name: 'Dr. V. Ulagamuthalvi', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F17', name: 'Dr.S. Prayla Shyry', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F18', name: 'Dr.N.S.Usha', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F19', name: 'Dr.D.Sudha', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F20', name: 'Dr. Deepa.V', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F21', name: 'Ms.K.Madhushri', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F22', name: 'Dr.G.M.Karpura Dheepan', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F23', name: 'Dr.P.M.Lavanya', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F24', name: 'Dr.P.Ranjana', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F25', name: 'Dr.V.Surya', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F26', name: 'Dr.T.Judgi', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F27', name: 'Dr.T.Anitha', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F28', name: 'Dr. S. Jancy', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F29', name: 'Ms.S.Hemalatha', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F30', name: 'Dr.M.Maheswari', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F31', name: 'Dr. J. Refonaa', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F32', name: 'Dr. M. D. Anto Praveena', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F33', name: 'Dr. S. Prince Mary', designation: 'Professor', department: 'CSE' },
  { facultyId: 'F34', name: 'Ms.Vanathi .M', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F35', name: 'Dr.D.Sheema', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F36', name: 'Dr. B. Ankayarkanni', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F37', name: 'Dr. D. Usha Nandini', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F38', name: 'Ms.Sandhiya.B', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F39', name: 'Ms.P.Kathambari', designation: 'Assistant Professor', department: 'CSE' },
  { facultyId: 'F40', name: 'Dr.D.Saravanan', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F41', name: 'Dr. A. Sindhuja', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F42', name: 'Dr.P.Rajaseka', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F43', name: 'Dr.K.Lalithadevi', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F44', name: 'Ms.Kalaivani A', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F45', name: 'Dr.D.Sudha', designation: 'Associate Professor', department: 'CSE' },
  { facultyId: 'F46', name: 'Dr.A.Mohana Priya ', designation: 'Associate Professor', department: 'CSE' }
];

export const INITIAL_TIMETABLES: TimetableEntry[] = [
  // --- MONDAY ---
  {
    id: 'T-MON-1A',
    day: 'MONDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C4',
    faculty: 'Dr. M. D. Anto Praveena / Dr. B. Ankayarkanni',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-1B',
    day: 'MONDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'D1',
    faculty: 'Dr.D.Saravanan / Dr. A. Sindhuja',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-2A',
    day: 'MONDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C4',
    faculty: 'Dr. M. D. Anto Praveena / Dr. B. Ankayarkanni',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  
  {
    id: 'T-MON-2B',
    day: 'MONDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'D1',
    faculty: 'Dr.D.Saravanan / Dr. A. Sindhuja',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-1C',
    day: 'MONDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E2',
    faculty: 'Dr.K.Lalithadev / Dr.D.Sudha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-2C',
    day: 'MONDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E3',
    faculty: 'Dr.A.Mohana Priya / Ms.Kalaivani A',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },  {
    id: 'T-MON-1D',
    day: 'MONDAY',
    period: 4,
    startTime: '12:15 AM',
    endTime: '01:15 PM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E2',
    faculty: 'Dr.K.Lalithadev / Dr.D.Sudha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-2D',
    day: 'MONDAY',
    period: 4,
    startTime: '12:15 AM',
    endTime: '01:15 PM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E3',
    faculty: 'Dr.A.Mohana Priya / Ms.Kalaivani A',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-5A',
    day: 'MONDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A1',
    faculty: 'Dr.Ramya G.Franklin / Dr.Shamreen Ahamed.B',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-5B',
    day: 'MONDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B1',
    faculty: 'Dr.R.Asha / Dr. V. Ulagamuthalvi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-5A',
    day: 'MONDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A1',
    faculty: 'Dr.Ramya G.Franklin / Dr.Shamreen Ahamed.B',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-MON-5B',
    day: 'MONDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B1',
    faculty: 'Dr.R.Asha / Dr. V. Ulagamuthalvi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },

  // --- TUESDAY ---
  {
    id: 'T-TUE-1A',
    day: 'TUESDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'III',
    department: 'CSE',
    subject: 'CBCS',
    subjectCode: 'SCSB4001',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C2',
    faculty: 'Dr. A.Mohana Priya',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-2A',
    day: 'TUESDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C2',
    faculty: 'Dr. M. D. Anto Praveena / Dr. S. Prince Mary',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-2B',
    day: 'TUESDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C5',
    faculty: 'Dr. D. Usha Nandini / Dr. B. Ankayarkanni',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-4A',
    day: 'TUESDAY',
    period: 4,
    startTime: '12:15 PM',
    endTime: '01:15 PM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C2',
    faculty: 'Dr. M. D. Anto Praveena / Dr. S. Prince Mary',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-4B',
    day: 'TUESDAY',
    period: 4,
    startTime: '12:15 PM',
    endTime: '01:15 PM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C5',
    faculty: 'Dr. D. Usha Nandini / Dr. B. Ankayarkanni',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-5A',
    day: 'TUESDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Software Engineering Design and Development',
    subjectCode: 'S11BLH51',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A2',
    faculty: 'Dr.T.Judgi / Dr.T.Anitha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-5B',
    day: 'TUESDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Augmented and Virtual Reality',
    subjectCode: 'S11BPB51',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B2',
    faculty: 'Dr.Srideivanai Nagarajan',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-6A',
    day: 'TUESDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Software Engineering Design and Development',
    subjectCode: 'S11BLH51',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A2',
    faculty: 'Dr.T.Judgi / Dr.T.Anitha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-TUE-6B',
    day: 'TUESDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Augmented and Virtual Reality',
    subjectCode: 'S11BPB51',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B2',
    faculty: 'Dr.Srideivanai Nagarajan',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },

  // --- WEDNESDAY ---
  {
    id: 'T-WED-1A',
    day: 'WEDNESDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B3',
    faculty: 'Dr. D. Usha Nandini / Dr. S. Prince Mary',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-1B',
    day: 'WEDNESDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B4',
    faculty: 'Ms.Sandhiya.B / Ms.P.Kathambari',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
    {
    id: 'T-WED-2A',
    day: 'WEDNESDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B3',
    faculty: 'Dr. D. Usha Nandini / Dr. S. Prince Mary',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-2B',
    day: 'WEDNESDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B4',
    faculty: 'Ms.Sandhiya.B / Ms.P.Kathambari',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-3A',
    day: 'WEDNESDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A1',
    faculty: 'Ms.P.Kabitha / Dr.A.Jemshia',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-3B',
    day: 'WEDNESDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B1',
    faculty: 'Dr. A. Pravin / Dr. T. Prem Jacob',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-4A',
    day: 'WEDNESDAY',
    period: 4,
    startTime: '12:15 pM',
    endTime: '01:15 PM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A1',
    faculty: 'Ms.P.Kabitha / Dr.A.Jemshia',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-4B',
    day: 'WEDNESDAY',
    period: 4,
    startTime: '12:15 pM',
    endTime: '01:15 PM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B1',
    faculty: 'Dr. A. Pravin / Dr. T. Prem Jacob',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-5A',
    day: 'WEDNESDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Augmented and Virtual Reality',
    subjectCode: 'S11BPB51',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C1',
    faculty: 'Dr.R.Rahin Batcha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-5B',
    day: 'WEDNESDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A3',
    faculty: 'Dr. V. Ulagamuthalvi / Dr.S. Prayla Shyry',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
    {
    id: 'T-WED-6A',
    day: 'WEDNESDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    year: 'III',
    department: 'CSE',
    subject: 'Augmented and Virtual Reality',
    subjectCode: 'S11BPB51',
    laboratory: 'Computer Society and Security Lab',
    batch: 'C1',
    faculty: 'Dr.R.Rahin Batcha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-WED-6B',
    day: 'WEDNESDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A3',
    faculty: 'Dr. V. Ulagamuthalvi / Dr.S. Prayla Shyry',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },

  // --- THURSDAY ---
  {
    id: 'T-THU-2A',
    day: 'THURSDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A5',
    faculty: 'Dr.M.Maheswari / Dr. J. Refonaa',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-THU-2B',
    day: 'THURSDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B2',
    faculty: 'Ms.Vanathi .M / Dr.D.Sheema',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-THU-4A',
    day: 'THURSDAY',
    period: 4,
    startTime: '12:15 PM',
    endTime: '01:15 PM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A5',
    faculty: 'Dr.M.Maheswari / Dr. J. Refonaa',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-THU-4B',
    day: 'THURSDAY',
    period: 4,
    startTime: '12:15 PM',
    endTime: '01:15 PM',
    year: 'II',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B2',
    faculty: 'Ms.Vanathi .M / Dr.D.Sheema',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-THU-5A',
    day: 'THURSDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A4',
    faculty: 'Dr. Deepa.V / Ms.K.Madhushri',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-THU-5B',
    day: 'THURSDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B4',
    faculty: 'Dr.G.M.Karpura Dheepan / Dr. L. K. Joshila Grace',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
    {
    id: 'T-THU-6A',
    day: 'THURSDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A4',
    faculty: 'Dr. Deepa.V / Ms.K.Madhushri',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-THU-6B',
    day: 'THURSDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B4',
    faculty: 'Dr.G.M.Karpura Dheepan / Dr. L. K. Joshila Grace',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },

  // --- FRIDAY ---
  {
    id: 'T-FRI-1A',
    day: 'FRIDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'D5',
    faculty: 'Dr.M.Maheswari / Dr. J. Refonaa',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-FRI-1B',
    day: 'FRIDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E5',
    faculty: 'Dr.Karthika.J / Ms.P.Kathambari',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
   {
    id: 'T-FRI-2A',
    day: 'FRIDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'D5',
    faculty: 'Dr.M.Maheswari / Dr. J. Refonaa',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-FRI-2B',
    day: 'FRIDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in Java',
    subjectCode: 'S12BLH31',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E5',
    faculty: 'Dr.Karthika.J / Ms.P.Kathambari',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
    {
    id: 'T-SAT-1C',
    day: 'FRIDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E2',
    faculty: 'Dr.K.Lalithadevi / Dr.D.Sudha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
      {
    id: 'T-SAT-1C',
    day: 'FRIDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 AM',
    year: 'I',
    department: 'CSE',
    subject: 'Programming in C',
    subjectCode: 'S11BLH11',
    laboratory: 'Computer Society and Security Lab',
    batch: 'E2',
    faculty: 'Dr.K.Lalithadevi / Dr.D.Sudha',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
      {
    id: 'T-SAT-1A',
    day: 'FRIDAY',
    period: 4,
    startTime: '11:15 AM',
    endTime: '12:15 AM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'D2',
    faculty: 'Dr.N.Sridevi / Ms.P.Malathi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-FRI-5A',
    day: 'FRIDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A5',
    faculty: 'Dr.P.M.Lavanya / Dr.P.Ranjana',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-FRI-5B',
    day: 'FRIDAY',
    period: 5,
    startTime: '01:15 PM',
    endTime: '02:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B5',
    faculty: 'Dr.V.Surya / Ms.K.Madhushri',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
    {
    id: 'T-FRI-5A',
    day: 'FRIDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A5',
    faculty: 'Dr.P.M.Lavanya / Dr.P.Ranjana',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-FRI-5B',
    day: 'FRIDAY',
    period: 6,
    startTime: '02:15 PM',
    endTime: '03:15 PM',
    year: 'III',
    department: 'CSE',
    subject: 'Computer Networks lab',
    subjectCode: 'SCSB2501',
    laboratory: 'Computer Society and Security Lab',
    batch: 'B5',
    faculty: 'Dr.V.Surya / Ms.K.Madhushri',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },

  // --- SATURDAY ---
  {
    id: 'T-SAT-1A',
    day: 'SATURDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A2',
    faculty: 'Dr.N.Sridevi / Ms.P.Malathi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-SAT-1B',
    day: 'SATURDAY',
    period: 1,
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'G1',
    faculty: 'Dr.Shamreen Ahamed.B / Dr.G.Subathra',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
   {
    id: 'T-SAT-1A',
    day: 'SATURDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A2',
    faculty: 'Dr.N.Sridevi / Ms.P.Malathi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-SAT-1B',
    day: 'SATURDAY',
    period: 2,
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'G1',
    faculty: 'Dr.Shamreen Ahamed.B / Dr.G.Subathra',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-SAT-3A',
    day: 'SATURDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'A1',
    faculty: 'Dr.L.K.Joshila Grace / Ms.D.Devi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  },
  {
    id: 'T-SAT-3B',
    day: 'SATURDAY',
    period: 3,
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    year: 'IV',
    department: 'CSE',
    subject: 'Big Data Analytics',
    subjectCode: 'S12BLH71',
    laboratory: 'Computer Society and Security Lab',
    batch: 'D1',
    faculty: 'Dr.P.Privietha / Ms.R.Velvizhi',
    room: "ST.PAUL'S BLOCK-GROUND FLOOR"
  }
];
